name: action_box
description: This package isolates business logic so that it can be reused.
version: 0.0.24
homepage: https://github.com/yookjy/action_box

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
